CarMarket/Areas/Admin/Controllers/CarController.cs
using CarMarket.Areas.Admin.Controllers;
using CarMarket.Services.Cars;
using CarMarket.Services.Dealers;
using CarMarket.Web.Areas.Admin.Models;
using CarMarket.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CarMarket.Areas.Admin.Constants.AdminConstants;

namespace CarMarket.Web.Areas.Admin.Controllers
{
    [Area(AreaName)]
    [Authorize(Roles = AdminRoleName)]
    public class CarController : AdminController
    {
        private readonly ICarService carService;
        private readonly IDealerService dealerService;

        public CarController(ICarService carService, IDealerService dealerService)
        {
            this.carService = carService;
            this.dealerService = dealerService;
        }

        [HttpGet]
        [Route("/Admin/Car/Mine")]
        public async Task<IActionResult> Mine()
        {
            var myCars = new MyCarsViewModel();
            var adminId = User.Id();
            myCars.BoughtCars = carService.AllCarsByUserId(adminId);
            var dealerId = dealerService.GetDealerId(adminId);
            myCars.AddedCars = carService.AllCarsByDealerId(dealerId);

            return View(myCars);
        }
    }
}

CarMarket/Areas/Admin/Controllers/UsersController.cs
using CarMarket.Services.Admins;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CarMarket.Areas.Admin.Constants.AdminConstants;

namespace CarMarket.Areas.Admin.Controllers
{
    [Area(AreaName)]
    [Authorize(Roles = AdminRoleName)]
    public class UsersController : AdminController
    {
        private readonly IUserService userService;

        public UsersController(IUserService _userService)
        {
            userService = _userService;
        }


        [HttpGet]
        [Route("/Admin/Users/ShowAllUsers")]
        public async Task<IActionResult> ShowAllUsers()
        {
            var model = userService.All();

            return View(model);
        }
    }
}

CarMarket/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarMarket - Administrator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/theme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarMarket.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <partial name="_UserMessages" />
    <header>
       <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="All">All Cars</a>
                        </li>
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Car" asp-action="Mine">My Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="ShowAllUsers">All Users</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <h1>Administaration dashboard</h1>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - CarMarket
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/lib/toastr/toastr.min.js"></script>
</body>
</html>