CarMarket/Areas/Admin/Controllers/CarController.cs
using CarMarket.Areas.Admin.Controllers;
using CarMarket.Services.Cars;
using CarMarket.Services.Dealers;
using CarMarket.Web.Areas.Admin.Models;
using CarMarket.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CarMarket.Areas.Admin.Constants.AdminConstants;

namespace CarMarket.Web.Areas.Admin.Controllers
{
    [Area(AreaName)]
    [Authorize(Roles = AdminRoleName)]
    public class CarController : AdminController
    {
        private readonly ICarService carService;
        private readonly IDealerService dealerService;

        public CarController(ICarService carService, IDealerService dealerService)
        {
            this.carService = carService;
            this.dealerService = dealerService;
        }

        [HttpGet]
        [Route("/Admin/Car/Mine")]
        public async Task<IActionResult> Mine()
        {
            var myCars = new MyCarsViewModel();
            var adminId = User.Id();
            myCars.BoughtCars = carService.AllCarsByUserId(adminId);
            var dealerId = dealerService.GetDealerId(adminId);
            myCars.AddedCars = carService.AllCarsByDealerId(dealerId);

            return View(myCars);
        }
    }
}

CarMarket/Controllers/DealerController.cs
using CarMarket.Services.Constants;
using CarMarket.Services.Dealers;
using CarMarket.Services.Models.Dealer;
using CarMarket.Web.Extensions;
using static CarMarket.Areas.Admin.Constants.AdminConstants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarMarket.Web.Controllers
{
    [Authorize]
    public class DealerController : Controller
    {
        private readonly IDealerService dealerService;

        public DealerController(IDealerService dealerService)
        {
            this.dealerService = dealerService;
        }

        [HttpGet]
        public async Task<IActionResult> Become()
        {
            if (dealerService.ExistsById(User.Id()))
            {
                TempData[MessageConstant.ErrorMessage] = "You are already a dealer!";

                return RedirectToAction("Index", "Home");
            }

            var model = new BecomeDealerModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeDealerModel model)
        {
            var userId = User.Id();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (dealerService.ExistsById(userId))
            {
                TempData[MessageConstant.ErrorMessage] = "You are already a dealer!";

                if (User.IsInRole(AdminRoleName))
                {
                    return RedirectToAction("Home", "Home", new { area = AreaName });
                }

                return RedirectToAction("Index", "Home");
            }

            if (dealerService.UserWithPhoneNumberExists(model.PhoneNumber))
            {
                TempData[MessageConstant.ErrorMessage] = "The phone already exists!";

                return RedirectToAction("Index", "Home");
            }

            if (dealerService.UserHasCars(userId))
            {
                TempData[MessageConstant.ErrorMessage] = "You must not have cars to become a dealer!";

                return RedirectToAction("Index", "Home");
            }

            dealerService.Create(userId, model.PhoneNumber);
            TempData[MessageConstant.SuccessMessage] = "You have successfully become a dealer!!";

            return RedirectToAction("Index", "Home");
        }
    }
}

CarMarket/Views/Shared/ShowAllUsers.cshtml
@using HouseRentingSystem.Core.Models.Admin
@model IEnumerable<UserServiceModel>

@{
    ViewBag.Title = "All Users";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th><label>Email</label></th>
            <th><label>Full Name</label></th>
            <th><label>Phone Number</label></th>
            <th><label>User Is Dealer</label></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td><label>@user.Email</label></td>
                <td><label>@user.FullName</label></td>
                <td><label>@user.PhoneNumber</label></td>
                <td>
                    @if (string.IsNullOrEmpty(user.PhoneNumber) == false)
                    {
                        <label>✔</label>
                    }
                    else
                    {
                        <label class="text-center">❌</label>
                    }
                </td>                
            </tr>
        }
    </tbody>
</table>

CarMarket/Views/Shared/_CarPartial.cshtml
@model CarModel

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageURL" alt="Car Image">
        <div class="card-body text-center">
            <h4>@Model.Make @Model.Model</h4>
            <h5>
                Price: <b>@Model.Price USD</b>
            </h5>
            <h6>Year Produced: <b>@Model.YearProduced</b></h6>
            <h6>Horsepower: <b>@Model.HorsePower</b></h6>
            <h6>Mileage: <b>@Model.Mileage</b></h6>
            <h6>Color: <b>@Model.Color</b></h6>
            
            <h6>(@(Model.IsBought ? "Bought" : "Not Bought"))</h6>
            <br />
            <a asp-area="" asp-controller="Car" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-success">Details</a>
            @if (this.User.IsInRole("Admin"))
            {              
                <a asp-area="" asp-controller="Car" asp-action="Delete" asp-route-id="@Model.Id"
               class="btn btn-danger">Delete</a>
                <p></p>
                @if (!Model.IsBought)
                {
                    <form asp-area="" asp-controller="Car"
                  asp-action="Buy" asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-primary" type="submit" value="Buy" />
                    </form>
                }
                else
                {
                    <form asp-area="" asp-controller="Car" asp-action="Sell"
                  asp-route-id="@Model.Id" method="post">
                        <input class="btn btn-primary" type="submit" value="Sell" />
                    </form>
                }
            }
        </div>
    </div>
</div>

CarMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarMarket</title>
    <link rel="stylesheet" href="~/css/theme.css"/>
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarMarket.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <partial name="_UserMessages" />
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarMarket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="All">All Cars</a>
                        </li>
                        @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Mine">My Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dealer" asp-action="Become">Become Dealer</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CarMarket
        </div>
    </footer>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
     <script src="~/lib/toastr/toastr.min.js"></script>  
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarMarket/Views/Shared/_UserMessages.cshtml
@using CarMarket.Services.Constants

@if (TempData[MessageConstant.ErrorMessage] != null)
{
    <script>
        $(function () { toastr.error('@TempData[MessageConstant.ErrorMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.WarningMessage] != null)
{
    <script>
        $(function () { toastr.warning('@TempData[MessageConstant.WarningMessage].ToString()'); });
    </script>
}

@if (TempData[MessageConstant.SuccessMessage] != null)
{
    <script>
        $(function () { toastr.success('@TempData[MessageConstant.SuccessMessage].ToString()'); });
    </script>
}